### ISSUE TITLE
Missing text?

### ISSUE THREAD

**Issue by dll128** [Artawower/second-brain-publisher#2]
https://github.com/Artawower/orgnote-cli/blame/2db8a0b08d6d94c3d4185107f3e88d56ad193c50/README.org#L92

Hello, forgive me, first time posting an issue. Hope I'm doing this right. Please forgive if not!

Text appears to be missing from the start of this line. Many thanks!!

**Comment by Artawower** [comment]
> Hello, forgive me, first time posting an issue. Hope I'm doing this right. Please forgive if not!

Don't worry, thats okay! 
Thanks for the issue, yep i lost some part of this phrase 🙂 Fixed last commit
